// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionquotagrant"
)

// SubscriptionQuotaGrantCreate is the builder for creating a SubscriptionQuotaGrant entity.
type SubscriptionQuotaGrantCreate struct {
	config
	mutation *SubscriptionQuotaGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionQuotaGrantCreate) SetSubscriptionID(v int64) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *SubscriptionQuotaGrantCreate) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetCycleStart sets the "cycle_start" field.
func (_c *SubscriptionQuotaGrantCreate) SetCycleStart(v time.Time) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetCycleStart(v)
	return _c
}

// SetGrantedUsd sets the "granted_usd" field.
func (_c *SubscriptionQuotaGrantCreate) SetGrantedUsd(v float64) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetGrantedUsd(v)
	return _c
}

// SetUsedUsd sets the "used_usd" field.
func (_c *SubscriptionQuotaGrantCreate) SetUsedUsd(v float64) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetUsedUsd(v)
	return _c
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_c *SubscriptionQuotaGrantCreate) SetNillableUsedUsd(v *float64) *SubscriptionQuotaGrantCreate {
	if v != nil {
		_c.SetUsedUsd(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionQuotaGrantCreate) SetStatus(v string) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionQuotaGrantCreate) SetNillableStatus(v *string) *SubscriptionQuotaGrantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *SubscriptionQuotaGrantCreate) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *SubscriptionQuotaGrantCreate) SetNillableRefundedAt(v *time.Time) *SubscriptionQuotaGrantCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionQuotaGrantCreate) SetCreatedAt(v time.Time) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionQuotaGrantCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionQuotaGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionQuotaGrantCreate) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionQuotaGrantCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionQuotaGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SubscriptionQuotaGrantMutation object of the builder.
func (_c *SubscriptionQuotaGrantCreate) Mutation() *SubscriptionQuotaGrantMutation {
	return _c.mutation
}

// Save creates the SubscriptionQuotaGrant in the database.
func (_c *SubscriptionQuotaGrantCreate) Save(ctx context.Context) (*SubscriptionQuotaGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionQuotaGrantCreate) SaveX(ctx context.Context) *SubscriptionQuotaGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionQuotaGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionQuotaGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionQuotaGrantCreate) defaults() {
	if _, ok := _c.mutation.UsedUsd(); !ok {
		v := subscriptionquotagrant.DefaultUsedUsd
		_c.mutation.SetUsedUsd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionquotagrant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionquotagrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionquotagrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionQuotaGrantCreate) check() error {
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.subscription_id"`)}
	}
	if _, ok := _c.mutation.PaymentOrderID(); !ok {
		return &ValidationError{Name: "payment_order_id", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.payment_order_id"`)}
	}
	if _, ok := _c.mutation.CycleStart(); !ok {
		return &ValidationError{Name: "cycle_start", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.cycle_start"`)}
	}
	if _, ok := _c.mutation.GrantedUsd(); !ok {
		return &ValidationError{Name: "granted_usd", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.granted_usd"`)}
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		return &ValidationError{Name: "used_usd", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.used_usd"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionquotagrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionQuotaGrant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionQuotaGrant.updated_at"`)}
	}
	return nil
}

func (_c *SubscriptionQuotaGrantCreate) sqlSave(ctx context.Context) (*SubscriptionQuotaGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionQuotaGrantCreate) createSpec() (*SubscriptionQuotaGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionQuotaGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionquotagrant.Table, sqlgraph.NewFieldSpec(subscriptionquotagrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = value
	}
	if value, ok := _c.mutation.CycleStart(); ok {
		_spec.SetField(subscriptionquotagrant.FieldCycleStart, field.TypeTime, value)
		_node.CycleStart = value
	}
	if value, ok := _c.mutation.GrantedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldGrantedUsd, field.TypeFloat64, value)
		_node.GrantedUsd = value
	}
	if value, ok := _c.mutation.UsedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUsedUsd, field.TypeFloat64, value)
		_node.UsedUsd = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionquotagrant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionQuotaGrant.Create().
//		SetSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionQuotaGrantUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionQuotaGrantCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionQuotaGrantUpsertOne {
	_c.conflict = opts
	return &SubscriptionQuotaGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionQuotaGrantCreate) OnConflictColumns(columns ...string) *SubscriptionQuotaGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionQuotaGrantUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionQuotaGrantUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionQuotaGrant node.
	SubscriptionQuotaGrantUpsertOne struct {
		create *SubscriptionQuotaGrantCreate
	}

	// SubscriptionQuotaGrantUpsert is the "OnConflict" setter.
	SubscriptionQuotaGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsert) SetSubscriptionID(v int64) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateSubscriptionID() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsert) AddSubscriptionID(v int64) *SubscriptionQuotaGrantUpsert {
	u.Add(subscriptionquotagrant.FieldSubscriptionID, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsert) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdatePaymentOrderID() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsert) AddPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsert {
	u.Add(subscriptionquotagrant.FieldPaymentOrderID, v)
	return u
}

// SetCycleStart sets the "cycle_start" field.
func (u *SubscriptionQuotaGrantUpsert) SetCycleStart(v time.Time) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldCycleStart, v)
	return u
}

// UpdateCycleStart sets the "cycle_start" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateCycleStart() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldCycleStart)
	return u
}

// SetGrantedUsd sets the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsert) SetGrantedUsd(v float64) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldGrantedUsd, v)
	return u
}

// UpdateGrantedUsd sets the "granted_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateGrantedUsd() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldGrantedUsd)
	return u
}

// AddGrantedUsd adds v to the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsert) AddGrantedUsd(v float64) *SubscriptionQuotaGrantUpsert {
	u.Add(subscriptionquotagrant.FieldGrantedUsd, v)
	return u
}

// SetUsedUsd sets the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsert) SetUsedUsd(v float64) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldUsedUsd, v)
	return u
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateUsedUsd() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldUsedUsd)
	return u
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsert) AddUsedUsd(v float64) *SubscriptionQuotaGrantUpsert {
	u.Add(subscriptionquotagrant.FieldUsedUsd, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionQuotaGrantUpsert) SetStatus(v string) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateStatus() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldStatus)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsert) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateRefundedAt() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsert) ClearRefundedAt() *SubscriptionQuotaGrantUpsert {
	u.SetNull(subscriptionquotagrant.FieldRefundedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionQuotaGrantUpsert) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantUpsert {
	u.Set(subscriptionquotagrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsert) UpdateUpdatedAt() *SubscriptionQuotaGrantUpsert {
	u.SetExcluded(subscriptionquotagrant.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionQuotaGrantUpsertOne) UpdateNewValues() *SubscriptionQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionquotagrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionQuotaGrantUpsertOne) Ignore() *SubscriptionQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionQuotaGrantUpsertOne) DoNothing() *SubscriptionQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionQuotaGrantCreate.OnConflict
// documentation for more info.
func (u *SubscriptionQuotaGrantUpsertOne) Update(set func(*SubscriptionQuotaGrantUpsert)) *SubscriptionQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionQuotaGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetSubscriptionID(v int64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsertOne) AddSubscriptionID(v int64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateSubscriptionID() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsertOne) AddPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdatePaymentOrderID() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetCycleStart sets the "cycle_start" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetCycleStart(v time.Time) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetCycleStart(v)
	})
}

// UpdateCycleStart sets the "cycle_start" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateCycleStart() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateCycleStart()
	})
}

// SetGrantedUsd sets the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetGrantedUsd(v float64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetGrantedUsd(v)
	})
}

// AddGrantedUsd adds v to the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsertOne) AddGrantedUsd(v float64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddGrantedUsd(v)
	})
}

// UpdateGrantedUsd sets the "granted_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateGrantedUsd() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateGrantedUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetUsedUsd(v float64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsertOne) AddUsedUsd(v float64) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateUsedUsd() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetStatus(v string) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateStatus() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateRefundedAt() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsertOne) ClearRefundedAt() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.ClearRefundedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionQuotaGrantUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertOne) UpdateUpdatedAt() *SubscriptionQuotaGrantUpsertOne {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionQuotaGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionQuotaGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionQuotaGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionQuotaGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionQuotaGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionQuotaGrantCreateBulk is the builder for creating many SubscriptionQuotaGrant entities in bulk.
type SubscriptionQuotaGrantCreateBulk struct {
	config
	err      error
	builders []*SubscriptionQuotaGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionQuotaGrant entities in the database.
func (_c *SubscriptionQuotaGrantCreateBulk) Save(ctx context.Context) ([]*SubscriptionQuotaGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionQuotaGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionQuotaGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionQuotaGrantCreateBulk) SaveX(ctx context.Context) []*SubscriptionQuotaGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionQuotaGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionQuotaGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionQuotaGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionQuotaGrantUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionQuotaGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionQuotaGrantUpsertBulk {
	_c.conflict = opts
	return &SubscriptionQuotaGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionQuotaGrantCreateBulk) OnConflictColumns(columns ...string) *SubscriptionQuotaGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionQuotaGrantUpsertBulk{
		create: _c,
	}
}

// SubscriptionQuotaGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionQuotaGrant nodes.
type SubscriptionQuotaGrantUpsertBulk struct {
	create *SubscriptionQuotaGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateNewValues() *SubscriptionQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionquotagrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionQuotaGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionQuotaGrantUpsertBulk) Ignore() *SubscriptionQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionQuotaGrantUpsertBulk) DoNothing() *SubscriptionQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionQuotaGrantCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionQuotaGrantUpsertBulk) Update(set func(*SubscriptionQuotaGrantUpsert)) *SubscriptionQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionQuotaGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetSubscriptionID(v int64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionQuotaGrantUpsertBulk) AddSubscriptionID(v int64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateSubscriptionID() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionQuotaGrantUpsertBulk) AddPaymentOrderID(v int64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdatePaymentOrderID() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetCycleStart sets the "cycle_start" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetCycleStart(v time.Time) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetCycleStart(v)
	})
}

// UpdateCycleStart sets the "cycle_start" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateCycleStart() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateCycleStart()
	})
}

// SetGrantedUsd sets the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetGrantedUsd(v float64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetGrantedUsd(v)
	})
}

// AddGrantedUsd adds v to the "granted_usd" field.
func (u *SubscriptionQuotaGrantUpsertBulk) AddGrantedUsd(v float64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddGrantedUsd(v)
	})
}

// UpdateGrantedUsd sets the "granted_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateGrantedUsd() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateGrantedUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetUsedUsd(v float64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *SubscriptionQuotaGrantUpsertBulk) AddUsedUsd(v float64) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateUsedUsd() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetStatus(v string) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateStatus() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateRefundedAt() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *SubscriptionQuotaGrantUpsertBulk) ClearRefundedAt() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.ClearRefundedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionQuotaGrantUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionQuotaGrantUpsertBulk) UpdateUpdatedAt() *SubscriptionQuotaGrantUpsertBulk {
	return u.Update(func(s *SubscriptionQuotaGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionQuotaGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionQuotaGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionQuotaGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionQuotaGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
