// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionquotagrant"
)

// SubscriptionQuotaGrant is the model entity for the SubscriptionQuotaGrant schema.
type SubscriptionQuotaGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID int64 `json:"payment_order_id,omitempty"`
	// CycleStart holds the value of the "cycle_start" field.
	CycleStart time.Time `json:"cycle_start,omitempty"`
	// GrantedUsd holds the value of the "granted_usd" field.
	GrantedUsd float64 `json:"granted_usd,omitempty"`
	// UsedUsd holds the value of the "used_usd" field.
	UsedUsd float64 `json:"used_usd,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RefundedAt holds the value of the "refunded_at" field.
	RefundedAt *time.Time `json:"refunded_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionQuotaGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionquotagrant.FieldGrantedUsd, subscriptionquotagrant.FieldUsedUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptionquotagrant.FieldID, subscriptionquotagrant.FieldSubscriptionID, subscriptionquotagrant.FieldPaymentOrderID:
			values[i] = new(sql.NullInt64)
		case subscriptionquotagrant.FieldStatus:
			values[i] = new(sql.NullString)
		case subscriptionquotagrant.FieldCycleStart, subscriptionquotagrant.FieldRefundedAt, subscriptionquotagrant.FieldCreatedAt, subscriptionquotagrant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionQuotaGrant fields.
func (_m *SubscriptionQuotaGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionquotagrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionquotagrant.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionquotagrant.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = value.Int64
			}
		case subscriptionquotagrant.FieldCycleStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_start", values[i])
			} else if value.Valid {
				_m.CycleStart = value.Time
			}
		case subscriptionquotagrant.FieldGrantedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_usd", values[i])
			} else if value.Valid {
				_m.GrantedUsd = value.Float64
			}
		case subscriptionquotagrant.FieldUsedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_usd", values[i])
			} else if value.Valid {
				_m.UsedUsd = value.Float64
			}
		case subscriptionquotagrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionquotagrant.FieldRefundedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_at", values[i])
			} else if value.Valid {
				_m.RefundedAt = new(time.Time)
				*_m.RefundedAt = value.Time
			}
		case subscriptionquotagrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionquotagrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionQuotaGrant.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionQuotaGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionQuotaGrant.
// Note that you need to call SubscriptionQuotaGrant.Unwrap() before calling this method if this SubscriptionQuotaGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionQuotaGrant) Update() *SubscriptionQuotaGrantUpdateOne {
	return NewSubscriptionQuotaGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionQuotaGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionQuotaGrant) Unwrap() *SubscriptionQuotaGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionQuotaGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionQuotaGrant) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionQuotaGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("payment_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentOrderID))
	builder.WriteString(", ")
	builder.WriteString("cycle_start=")
	builder.WriteString(_m.CycleStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("granted_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantedUsd))
	builder.WriteString(", ")
	builder.WriteString("used_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedUsd))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.RefundedAt; v != nil {
		builder.WriteString("refunded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionQuotaGrants is a parsable slice of SubscriptionQuotaGrant.
type SubscriptionQuotaGrants []*SubscriptionQuotaGrant
