// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionquotagrant"
)

// SubscriptionQuotaGrantUpdate is the builder for updating SubscriptionQuotaGrant entities.
type SubscriptionQuotaGrantUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionQuotaGrantMutation
}

// Where appends a list predicates to the SubscriptionQuotaGrantUpdate builder.
func (_u *SubscriptionQuotaGrantUpdate) Where(ps ...predicate.SubscriptionQuotaGrant) *SubscriptionQuotaGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionQuotaGrantUpdate) SetSubscriptionID(v int64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionQuotaGrantUpdate) AddSubscriptionID(v int64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionQuotaGrantUpdate) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillablePaymentOrderID(v *int64) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionQuotaGrantUpdate) AddPaymentOrderID(v int64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetCycleStart sets the "cycle_start" field.
func (_u *SubscriptionQuotaGrantUpdate) SetCycleStart(v time.Time) *SubscriptionQuotaGrantUpdate {
	_u.mutation.SetCycleStart(v)
	return _u
}

// SetNillableCycleStart sets the "cycle_start" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableCycleStart(v *time.Time) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetCycleStart(*v)
	}
	return _u
}

// SetGrantedUsd sets the "granted_usd" field.
func (_u *SubscriptionQuotaGrantUpdate) SetGrantedUsd(v float64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.ResetGrantedUsd()
	_u.mutation.SetGrantedUsd(v)
	return _u
}

// SetNillableGrantedUsd sets the "granted_usd" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableGrantedUsd(v *float64) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetGrantedUsd(*v)
	}
	return _u
}

// AddGrantedUsd adds value to the "granted_usd" field.
func (_u *SubscriptionQuotaGrantUpdate) AddGrantedUsd(v float64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.AddGrantedUsd(v)
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *SubscriptionQuotaGrantUpdate) SetUsedUsd(v float64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableUsedUsd(v *float64) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *SubscriptionQuotaGrantUpdate) AddUsedUsd(v float64) *SubscriptionQuotaGrantUpdate {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionQuotaGrantUpdate) SetStatus(v string) *SubscriptionQuotaGrantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableStatus(v *string) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *SubscriptionQuotaGrantUpdate) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdate) SetNillableRefundedAt(v *time.Time) *SubscriptionQuotaGrantUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *SubscriptionQuotaGrantUpdate) ClearRefundedAt() *SubscriptionQuotaGrantUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionQuotaGrantUpdate) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionQuotaGrantMutation object of the builder.
func (_u *SubscriptionQuotaGrantUpdate) Mutation() *SubscriptionQuotaGrantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionQuotaGrantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionQuotaGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionQuotaGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionQuotaGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionQuotaGrantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionquotagrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionQuotaGrantUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionquotagrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionQuotaGrant.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionQuotaGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionquotagrant.Table, subscriptionquotagrant.Columns, sqlgraph.NewFieldSpec(subscriptionquotagrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionquotagrant.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionquotagrant.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CycleStart(); ok {
		_spec.SetField(subscriptionquotagrant.FieldCycleStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GrantedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldGrantedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedUsd(); ok {
		_spec.AddField(subscriptionquotagrant.FieldGrantedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(subscriptionquotagrant.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionquotagrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(subscriptionquotagrant.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionquotagrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionQuotaGrantUpdateOne is the builder for updating a single SubscriptionQuotaGrant entity.
type SubscriptionQuotaGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionQuotaGrantMutation
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetSubscriptionID(v int64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionQuotaGrantUpdateOne) AddSubscriptionID(v int64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetPaymentOrderID(v int64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillablePaymentOrderID(v *int64) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionQuotaGrantUpdateOne) AddPaymentOrderID(v int64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetCycleStart sets the "cycle_start" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetCycleStart(v time.Time) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.SetCycleStart(v)
	return _u
}

// SetNillableCycleStart sets the "cycle_start" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableCycleStart(v *time.Time) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetCycleStart(*v)
	}
	return _u
}

// SetGrantedUsd sets the "granted_usd" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetGrantedUsd(v float64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.ResetGrantedUsd()
	_u.mutation.SetGrantedUsd(v)
	return _u
}

// SetNillableGrantedUsd sets the "granted_usd" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableGrantedUsd(v *float64) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetGrantedUsd(*v)
	}
	return _u
}

// AddGrantedUsd adds value to the "granted_usd" field.
func (_u *SubscriptionQuotaGrantUpdateOne) AddGrantedUsd(v float64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.AddGrantedUsd(v)
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetUsedUsd(v float64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableUsedUsd(v *float64) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *SubscriptionQuotaGrantUpdateOne) AddUsedUsd(v float64) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetStatus(v string) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableStatus(v *string) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetRefundedAt(v time.Time) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *SubscriptionQuotaGrantUpdateOne) SetNillableRefundedAt(v *time.Time) *SubscriptionQuotaGrantUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *SubscriptionQuotaGrantUpdateOne) ClearRefundedAt() *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionQuotaGrantUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionQuotaGrantMutation object of the builder.
func (_u *SubscriptionQuotaGrantUpdateOne) Mutation() *SubscriptionQuotaGrantMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionQuotaGrantUpdate builder.
func (_u *SubscriptionQuotaGrantUpdateOne) Where(ps ...predicate.SubscriptionQuotaGrant) *SubscriptionQuotaGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionQuotaGrantUpdateOne) Select(field string, fields ...string) *SubscriptionQuotaGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionQuotaGrant entity.
func (_u *SubscriptionQuotaGrantUpdateOne) Save(ctx context.Context) (*SubscriptionQuotaGrant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionQuotaGrantUpdateOne) SaveX(ctx context.Context) *SubscriptionQuotaGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionQuotaGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionQuotaGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionQuotaGrantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionquotagrant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionQuotaGrantUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionquotagrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionQuotaGrant.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionQuotaGrantUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionQuotaGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionquotagrant.Table, subscriptionquotagrant.Columns, sqlgraph.NewFieldSpec(subscriptionquotagrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionQuotaGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionquotagrant.FieldID)
		for _, f := range fields {
			if !subscriptionquotagrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionquotagrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionquotagrant.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionquotagrant.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionquotagrant.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CycleStart(); ok {
		_spec.SetField(subscriptionquotagrant.FieldCycleStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GrantedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldGrantedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedUsd(); ok {
		_spec.AddField(subscriptionquotagrant.FieldGrantedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(subscriptionquotagrant.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionquotagrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(subscriptionquotagrant.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionquotagrant.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionQuotaGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionquotagrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
