// Code generated by ent, DO NOT EDIT.

package subscriptionquotagrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptionquotagrant type in the database.
	Label = "subscription_quota_grant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldCycleStart holds the string denoting the cycle_start field in the database.
	FieldCycleStart = "cycle_start"
	// FieldGrantedUsd holds the string denoting the granted_usd field in the database.
	FieldGrantedUsd = "granted_usd"
	// FieldUsedUsd holds the string denoting the used_usd field in the database.
	FieldUsedUsd = "used_usd"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRefundedAt holds the string denoting the refunded_at field in the database.
	FieldRefundedAt = "refunded_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the subscriptionquotagrant in the database.
	Table = "subscription_quota_grants"
)

// Columns holds all SQL columns for subscriptionquotagrant fields.
var Columns = []string{
	FieldID,
	FieldSubscriptionID,
	FieldPaymentOrderID,
	FieldCycleStart,
	FieldGrantedUsd,
	FieldUsedUsd,
	FieldStatus,
	FieldRefundedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsedUsd holds the default value on creation for the "used_usd" field.
	DefaultUsedUsd float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionQuotaGrant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByCycleStart orders the results by the cycle_start field.
func ByCycleStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCycleStart, opts...).ToFunc()
}

// ByGrantedUsd orders the results by the granted_usd field.
func ByGrantedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedUsd, opts...).ToFunc()
}

// ByUsedUsd orders the results by the used_usd field.
func ByUsedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedUsd, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRefundedAt orders the results by the refunded_at field.
func ByRefundedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
