// Code generated by ent, DO NOT EDIT.

package subscriptionquotagrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldID, id))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldSubscriptionID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldPaymentOrderID, v))
}

// CycleStart applies equality check predicate on the "cycle_start" field. It's identical to CycleStartEQ.
func CycleStart(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldCycleStart, v))
}

// GrantedUsd applies equality check predicate on the "granted_usd" field. It's identical to GrantedUsdEQ.
func GrantedUsd(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldGrantedUsd, v))
}

// UsedUsd applies equality check predicate on the "used_usd" field. It's identical to UsedUsdEQ.
func UsedUsd(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldUsedUsd, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldStatus, v))
}

// RefundedAt applies equality check predicate on the "refunded_at" field. It's identical to RefundedAtEQ.
func RefundedAt(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldRefundedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldSubscriptionID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldPaymentOrderID, v))
}

// CycleStartEQ applies the EQ predicate on the "cycle_start" field.
func CycleStartEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldCycleStart, v))
}

// CycleStartNEQ applies the NEQ predicate on the "cycle_start" field.
func CycleStartNEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldCycleStart, v))
}

// CycleStartIn applies the In predicate on the "cycle_start" field.
func CycleStartIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldCycleStart, vs...))
}

// CycleStartNotIn applies the NotIn predicate on the "cycle_start" field.
func CycleStartNotIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldCycleStart, vs...))
}

// CycleStartGT applies the GT predicate on the "cycle_start" field.
func CycleStartGT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldCycleStart, v))
}

// CycleStartGTE applies the GTE predicate on the "cycle_start" field.
func CycleStartGTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldCycleStart, v))
}

// CycleStartLT applies the LT predicate on the "cycle_start" field.
func CycleStartLT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldCycleStart, v))
}

// CycleStartLTE applies the LTE predicate on the "cycle_start" field.
func CycleStartLTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldCycleStart, v))
}

// GrantedUsdEQ applies the EQ predicate on the "granted_usd" field.
func GrantedUsdEQ(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldGrantedUsd, v))
}

// GrantedUsdNEQ applies the NEQ predicate on the "granted_usd" field.
func GrantedUsdNEQ(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldGrantedUsd, v))
}

// GrantedUsdIn applies the In predicate on the "granted_usd" field.
func GrantedUsdIn(vs ...float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldGrantedUsd, vs...))
}

// GrantedUsdNotIn applies the NotIn predicate on the "granted_usd" field.
func GrantedUsdNotIn(vs ...float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldGrantedUsd, vs...))
}

// GrantedUsdGT applies the GT predicate on the "granted_usd" field.
func GrantedUsdGT(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldGrantedUsd, v))
}

// GrantedUsdGTE applies the GTE predicate on the "granted_usd" field.
func GrantedUsdGTE(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldGrantedUsd, v))
}

// GrantedUsdLT applies the LT predicate on the "granted_usd" field.
func GrantedUsdLT(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldGrantedUsd, v))
}

// GrantedUsdLTE applies the LTE predicate on the "granted_usd" field.
func GrantedUsdLTE(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldGrantedUsd, v))
}

// UsedUsdEQ applies the EQ predicate on the "used_usd" field.
func UsedUsdEQ(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedUsdNEQ applies the NEQ predicate on the "used_usd" field.
func UsedUsdNEQ(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldUsedUsd, v))
}

// UsedUsdIn applies the In predicate on the "used_usd" field.
func UsedUsdIn(vs ...float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldUsedUsd, vs...))
}

// UsedUsdNotIn applies the NotIn predicate on the "used_usd" field.
func UsedUsdNotIn(vs ...float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldUsedUsd, vs...))
}

// UsedUsdGT applies the GT predicate on the "used_usd" field.
func UsedUsdGT(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldUsedUsd, v))
}

// UsedUsdGTE applies the GTE predicate on the "used_usd" field.
func UsedUsdGTE(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldUsedUsd, v))
}

// UsedUsdLT applies the LT predicate on the "used_usd" field.
func UsedUsdLT(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldUsedUsd, v))
}

// UsedUsdLTE applies the LTE predicate on the "used_usd" field.
func UsedUsdLTE(v float64) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldUsedUsd, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldContainsFold(FieldStatus, v))
}

// RefundedAtEQ applies the EQ predicate on the "refunded_at" field.
func RefundedAtEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundedAtNEQ applies the NEQ predicate on the "refunded_at" field.
func RefundedAtNEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldRefundedAt, v))
}

// RefundedAtIn applies the In predicate on the "refunded_at" field.
func RefundedAtIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldRefundedAt, vs...))
}

// RefundedAtNotIn applies the NotIn predicate on the "refunded_at" field.
func RefundedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldRefundedAt, vs...))
}

// RefundedAtGT applies the GT predicate on the "refunded_at" field.
func RefundedAtGT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldRefundedAt, v))
}

// RefundedAtGTE applies the GTE predicate on the "refunded_at" field.
func RefundedAtGTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldRefundedAt, v))
}

// RefundedAtLT applies the LT predicate on the "refunded_at" field.
func RefundedAtLT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldRefundedAt, v))
}

// RefundedAtLTE applies the LTE predicate on the "refunded_at" field.
func RefundedAtLTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldRefundedAt, v))
}

// RefundedAtIsNil applies the IsNil predicate on the "refunded_at" field.
func RefundedAtIsNil() predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIsNull(FieldRefundedAt))
}

// RefundedAtNotNil applies the NotNil predicate on the "refunded_at" field.
func RefundedAtNotNil() predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotNull(FieldRefundedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionQuotaGrant) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionQuotaGrant) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionQuotaGrant) predicate.SubscriptionQuotaGrant {
	return predicate.SubscriptionQuotaGrant(sql.NotPredicates(p))
}
